name: Marcus Crane
email: marcus@utf9k.net
social:
  github: marcus-crane
  twitter: sentreh
work:
  email: marcus.crane@lightspeedhq.com
  website: https://www.vendhq.com/nz/
languages:
  aria2: 1.36.0
  bat: 0.23.0
  chezmoi: 2.40.0
  container-diff: 0.17.0
  crystal:
    home: 1.9.2
    work: null
  cue: 0.6.0
  dive: 0.11.0
  dotenv-linter: 3.3.0
  exa: 0.10.1
  github-markdown-toc: 1.3.0
  golang: 1.21.1
  goreleaser: 1.21.2
  ghorg: 1.9.9
  hadolint: v2.12.0
  hugo: latest
  lua: 5.4.3
  neovim: 0.9.2
  nodejs: lts
  python: 3.12.0
  ruby:
    home: 3.0.2
    work: null
  rust: nightly
  shellcheck: 0.9.0
  shellspec: 0.28.1
  sqlite: 3.43.1
  terraform: 1.5.7
  terraform-docs: 0.16.0
  tmux: 3.3
libraries:
  cargo:
    installer: cargo install
    # cargo install --features=pcre2 ripgrep
    # Requires a custom flag
    # TODO: Add generic flag support to my wonky installer?
    global:
      - git-cliff
  go:
    installer: go install
    global:
      - github.com/cweill/gotests/...@latest
      - github.com/fatih/gomodifytags@latest
      - github.com/go-delve/delve/cmd/dlv@latest
      - github.com/mdempsky/gocode@latest
      - github.com/segmentio/golines@latest
      - github.com/x-motemen/gore/cmd/gore@latest
      - golang.org/x/tools/cmd/goimports@latest
      - golang.org/x/tools/cmd/guru@latest
      - mvdan.cc/gofumpt@latest
    home:
      - github.com/wailsapp/wails/v2/cmd/wails@latest
    work:
      - github.com/golang/mock/mockgen@v1.6.0
  npm:
    installer: npm install -g
    global:
      - eslint
      - js-beautify
      - neovim
      - npm
      - pkgparse
      - pnpm
      - stylelint
      - tree-sitter-cli
      - yarn
    work:
      - "@datadog/datadog-ci"
  python:
    installer: pip install -U
    global:
      - Django
      - PyGithub
      - beautifulsoup4
      - black
      - devdeck
      - devdeck-macos
      - devdeck-slack
      - dnspython
      - flake8
      - kazoo
      - isort
      - mkdocs
      - nose
      - pip
      - poetry
      - pynvim
      - pyyaml
      - requests
    home:
      - beets
      - pylast
      - pyusb
    work:
      - ansible
      - mkdocs-techdocs-core
  ruby:
    installer: gem install
    global:
      - bundler
      - neovim
