name: Marcus Crane
email: marcus@utf9k.net
social:
  github: marcus-crane
  twitter: sentreh
work:
  email: marcus.crane@lightspeedhq.com
  website: https://www.vendhq.com/nz/
languages:
  aria2: 1.36.0
  bat: 0.22.1
  chezmoi: 2.27.1
  container-diff: 0.17.0
  crystal:
    home: 1.6.2
    work: null
  cue: 0.4.3
  dive: 0.10.0
  dotenv-linter: 3.2.0
  elixir:
    home: 1.14.3
    work: null
  erlang:
    home: 25.3
    work: null
  exa: 0.10.1
  flutter:
    home: 3.3.9-stable
    work: null
  github-markdown-toc: 1.2.0
  golang: 1.19.3
  goreleaser: 1.13.0
  ghorg: 1.9.0
  hadolint: v2.12.0
  hugo: latest
  lua: 5.4.3
  neovim: 0.7.0
  nodejs: lts
  python: 3.9.9
  ruby: 3.0.2
  rust: nightly
  saml2aws:
    home: null
    work: 2.36.1
  shellcheck: 0.8.0
  shellspec: 0.28.1
  steampipe: 0.17.2
  sqlite: 3.40.0
  terraform:
    home: 1.3.6
    work: 0.13.7
  terraform-docs: 0.16.0
  tmux: 3.3
  upx:
    home: 4.0.1
    work: null
libraries:
  cargo:
    installer: cargo install
    global:
      - git-cliff
  go:
    installer: go install
    global:
      - github.com/cweill/gotests/...@latest
      - github.com/fatih/gomodifytags@latest
      - github.com/go-delve/delve/cmd/dlv@latest
      - github.com/mdempsky/gocode@latest
      - github.com/segmentio/golines@latest
      - github.com/x-motemen/gore/cmd/gore@latest
      - golang.org/x/tools/cmd/goimports@latest
      - golang.org/x/tools/cmd/guru@latest
      - mvdan.cc/gofumpt@latest
    home:
      - github.com/wailsapp/wails/v2/cmd/wails@latest
    work:
      - github.com/golang/mock/mockgen@v1.6.0
  npm:
    installer: npm install -g
    global:
      - eslint
      - js-beautify
      - neovim
      - npm
      - pkgparse
      - pnpm
      - stylelint
      - tree-sitter-cli
      - yarn
    work:
      - "@datadog/datadog-ci"
  python:
    installer: pip install -U
    global:
      - Django
      - PyGithub
      - beautifulsoup4
      - black
      - devdeck
      - devdeck-macos
      - devdeck-slack
      - dnspython
      - flake8
      - kazoo
      - isort
      - mkdocs
      - nose
      - pip
      - poetry
      - pynvim
      - pyyaml
      - requests
    home:
      - beets
      - pylast
      - pyusb
    work:
      - ansible
      - mkdocs-techdocs-core
  ruby:
    installer: gem install
    global:
      - bundler
      - neovim
