name: Marcus Crane
email: marcus@utf9k.net
social:
  github: marcus-crane
  twitter: sentreh
work:
  email: marcus.crane@lightspeedhq.com
  website: https://www.vendhq.com/nz/
languages:
  aria2: 1.36.0
  cue: 0.4.2
  crystal:
    home: 1.4.0
    work: null
  dive: 0.10.0
  exa: 0.10.1
  gohugo: 0.97.3
  golang: 1.18
  goreleaser: 1.7.0
  hadolint: v2.10.0
  lua: 5.4.3
  mitmproxy:
    home: 8.0.0
    work: null
  neovim: 0.6.1
  nodejs: lts
  python: 3.9.9
  ruby: 3.0.2
  rust: nightly
  saml2aws: 2.34.0
  shellcheck: 0.8.0
  shellspec: 0.28.1
  sqlite: 3.38.2
  terraform:
    home: 1.0.10
    work: 0.13.7
  tmux: 3.2
  upx:
    home: 3.96
    work: null
  yarn: 1.22.18
libraries:
  go:
    installer: go install
    global:
      - github.com/cweill/gotests/...@latest
      - github.com/fatih/gomodifytags@latest
      - github.com/go-delve/delve/cmd/dlv@latest
      - github.com/mdempsky/gocode@latest
      - github.com/segmentio/golines@latest
      - github.com/x-motemen/gore/cmd/gore@latest
      - golang.org/x/tools/cmd/goimports@latest
      - golang.org/x/tools/cmd/guru@latest
      - mvdan.cc/gofumpt@latest
    home:
      - github.com/wailsapp/wails/v2/cmd/wails@latest
    work:
      - github.com/golang/mock/mockgen@v1.6.0
  npm:
    installer: npm install -g
    global:
      - eslint
      - js-beautify
      - neovim
      - npm
      - pkgparse
      - pnpm
      - stylelint
      - tree-sitter-cli
      - yarn
    work:
      - "@datadog/datadog-ci"
  python:
    installer: pip install -U
    global:
      - Django
      - PyGithub
      - beautifulsoup4
      - black
      - devdeck
      - devdeck-macos
      - devdeck-slack
      - dnspython
      - flake8
      - isort
      - mkdocs
      - nose
      - pip
      - poetry
      - pynvim
      - pyyaml
      - requests
    home:
      - beets
      - pylast
      - pyusb
    work:
      - ansible
      - mkdocs-techdocs-core
  ruby:
    installer: gem install
    global:
      - bundler
      - neovim