name: Marcus Crane
email: marcus@utf9k.net
social:
  github: marcus-crane
work:
  email: marcus.crane@lightspeedhq.com
  website: https://www.lightspeedhq.com.au
languages:
  awscli:
    home: null
    work: 2.13.38
  bun: 1.0.26
  container-diff: 0.17.0
  crystal: 1.11.2
  cue: 0.6.0
  deno: 1.38.4
  dive: 0.11.0
  dotenv-linter: 3.3.0
  github-markdown-toc: 1.2.0
  golang: 1.22.0
  goreleaser: 1.21.2
  hugo: 0.119.0
  lua: 5.1
  neovim: 0.9.5
  nodejs: 20.8.0
  python: 3.11.0
  ruby: 3.3.0
  rust: nightly
  shellcheck: 0.9.0
  shellspec: 0.28.1
  sqlite: 3.43.1
  terraform:
    home: 1.7.3
    work: 1.4.5
  tmux: 3.3
libraries:
  cargo:
    installer: cargo install
    # cargo install --features=pcre2 ripgrep
    # Requires a custom flag
    # TODO: Add generic flag support to my wonky installer?
    global:
      - git-cliff
  go:
    installer: go install
    global:
      - github.com/cweill/gotests/...@latest
      - github.com/fatih/gomodifytags@latest
      - github.com/go-delve/delve/cmd/dlv@latest
      - github.com/mdempsky/gocode@latest
      - github.com/segmentio/golines@latest
      - github.com/x-motemen/gore/cmd/gore@latest
      - golang.org/x/tools/cmd/goimports@latest
      - golang.org/x/tools/cmd/guru@latest
      - mvdan.cc/gofumpt@latest
    home:
      - github.com/wailsapp/wails/v2/cmd/wails@latest
    work:
      - github.com/golang/mock/mockgen@v1.6.0
  npm:
    installer: npm install -g
    global:
      - eslint
      - js-beautify
      - neovim
      - npm
      - pkgparse
      - pnpm
      - stylelint
      - tree-sitter-cli
      - yarn
    work:
      - "@datadog/datadog-ci"
  python:
    installer: pip install -U
    global:
      - Django
      - PyGithub
      - beautifulsoup4
      - black
      - devdeck
      - devdeck-macos
      - devdeck-slack
      - dnspython
      - flake8
      - kazoo
      - isort
      - mkdocs
      - nose
      - pip
      - poetry
      - pynvim
      - pyyaml
      - requests
    home:
      - beets
      - beets-vgmdb
      - pylast
      - pyusb
    work:
      - ansible
      - mkdocs-techdocs-core
  ruby:
    installer: gem install
    global:
      - bundler
      - neovim
