name: Marcus Crane
email: marcus@utf9k.net
social:
  github: marcus-crane
  twitter: sentreh
work:
  email: marcus.crane@lightspeedhq.com
  website: https://www.vendhq.com/nz/
languages:
  terraform:
    home: 1.0.10
    work: 0.13.7