name: Marcus Crane
email: marcus@utf9k.net
social:
  github: marcus-crane
work:
  email: marcus.crane@lightspeedhq.com
  website: https://www.lightspeedhq.com.au
tools:
  awscli:
    home: null
    work: 2.22.23
  bun: 1.1.42
  crystal: 1.14.0
  deno: 2.1.4
  dive: 0.12.0
  golang: 1.23.4
  lua: 5.1
  neovim: 0.10.3
  nodejs: 23.5.0
  python:
    home: 3.11.0
    work: 3.10.0
  ruby: 3.3.6
  rust: nightly
  shellcheck: 0.10.0
  shellspec: 0.28.1
  sqlite: 3.47.2
  terraform:
    home: 1.10.3
    work: 1.4.5
  vale: 3.9.2
  yt-dlp: 2024.12.23
libraries:
  cargo:
    installer: cargo install
    # cargo install --features=pcre2 ripgrep
    # Requires a custom flag
    # TODO: Add generic flag support to my wonky installer?
    global:
      - git-cliff
  go:
    installer: go install
    global:
      - github.com/cweill/gotests/...@latest
      - github.com/fatih/gomodifytags@latest
      - github.com/go-delve/delve/cmd/dlv@latest
      - github.com/mdempsky/gocode@latest
      - github.com/segmentio/golines@latest
      - github.com/x-motemen/gore/cmd/gore@latest
      - golang.org/x/tools/cmd/goimports@latest
      - golang.org/x/tools/cmd/guru@latest
      - mvdan.cc/gofumpt@latest
    home:
      - github.com/wailsapp/wails/v2/cmd/wails@latest
    work:
      - github.com/golang/mock/mockgen@v1.6.0
  npm:
    installer: npm install -g
    global:
      - eslint
      - js-beautify
      - neovim
      - npm
      - pnpm
      - stylelint
      - tree-sitter-cli
      - yarn
    work:
      - "@datadog/datadog-ci"
  python:
    installer: pip install -U
    global:
      - Django
      - PyGithub
      - beautifulsoup4
      - black
      - dnspython
      - flake8
      - kazoo
      - isort
      - mkdocs
      - nose
      - pip
      - poetry
      - pynvim
      - pyyaml
      - requests
    home:
      - beets
      - beets-vgmdb
      - pylast
      - pyusb
    work:
      - ansible
      - mkdocs-techdocs-core
  ruby:
    installer: gem install
    global:
      - bundler
      - neovim
