site_name: dotfiles
site_url: https://dotfiles.utf9k.net
repo_name: marcus-crane/dotfiles
repo_url: https://github.com/marcus-crane/dotfiles
site_author: Marcus Crane <marcus@utf9k.net>

nav:
  - .zshrc: zshrc.md
  - ssh:
    - authorized_keys: authorized_keys.tmpl.md
  - Graveyard:
    - .zshrc: zshrc-graveyard.md
  - Playground: playground.md

markdown_extensions:
  - toc:
      baselevel: 3

plugins:
  - techdocs-core
