site_name: dotfiles
site_url: https://dotfiles.utf9k.net
repo_url: https://github.com/marcus-crane/dotfiles
site_author: Marcus Crane <marcus@utf9k.net>

nav:
  - 'Shell Configuration':
      - .zshrc: 'zshrc.md'
  - Archives:
    - zshrc graveyard: 'zshrc-graveyard.md'
  - Playground: 'playground.md'

markdown_extensions:
  - toc:
      baselevel: 3

plugins:
  - techdocs-core
