[build]
publish = "site"
command = "mkdir docs && find . -name '*.md' | xargs -I{} mv '{}' docs && pip install mkdocs mkdocs-techdocs-core && mkdocs build"

[build.environment]
PYTHON_VERSION = "3.8"
