#+title: dotfiles

Want to browse this repo like a website? Start [[https://dots.utf9k.net/][here]]

I recently came across [[https://twitter.com/brandoninvergo][Brandon Invergo]]'s [[http://brandon.invergo.net/news/2012-05-26-using-gnu-stow-to-manage-your-dotfiles.html][blog post]] about [[https://www.gnu.org/software/stow/][GNU Stow]] after battling with dotfile configuration for quite some time.

The top level files are simply categories and running ~stow {folder name}~ on them will symlink the contents to ~$HOME~.

For example, let's say you used ~stow~ on ~mopidy/.config/mopidy~. It would ignore the top level directory and starting from
~$HOME~ (eg; ~/home/marcus~), it would place the folder in ~home/marcus/.config/mopidy~.

The nice thing about it is that everything is kept organised in one folder but you don't have to worry about conflicts since you need to explicitly use stow on each folder.

## A note on tangling files

You may notice that some configuration files are seemingly missing with `.org` files in their place.

This is because a few, and in time most of, my config files are kept as "literate configuration".

In short, all of the surrounding commentary is stripped and the correct file is generated off of the source code blocks.

In order to "tangle" them into a proper config, you'll need to have `emacs` installed.

Assuming it's installed, you can "tangle" the file you're interested in like so:

#+begin_src bash
~/.emacs.d/bin/org-tangle <config_path>
#+end_src
