#+title: My Doom Emacs configuration
#+options: toc:2
#+startup: content
#+property: header-args :tangle config.el
#+setupfile: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup

# Local variables:
# eval: (add-hook 'after-save-hook 'org-html-export-to-html t t)
# end:

* Core setup
** Lexical binding
#+begin_src emacs-lisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+end_src
** User details
#+begin_src emacs-lisp
(setq user-full-name "Marcus Crane"
      user-mail-address "marcus@utf9k.net")
#+end_src
** Theming
#+begin_src emacs-lisp
(setq doom-theme 'doom-one)
#+end_src
** Dropbox
I make use of [[https://dropbox.com][Dropbox]] to sync and store my org files.

The location of Dropbox differs between all of my machines so I have an environment variable, ~$DROPBOX_DIR~, set by my shell.

On some systems, it may live in my home directory while on others, it may live on an external hard drive for example.

NOTE: This will (unfortunately) set a hard dependency on Dropbox existing. If it isn't present, most of my Emacs config will break.

#+begin_src emacs-lisp
(setq dropbox       (getenv "DROPBOX_DIR")
      dropbox-org   (concat dropbox "/org/")
      dropbox-tmpl  (concat dropbox-org "/templates/")
      dropbox-notes (concat dropbox-org "/notes/"))
#+end_src
** Common files
Here are some variables for locations I often access, or want to encourage myself to access
#+begin_src emacs-lisp
(setq workspace     (getenv "WORKSPACE")
      utf9k-notes   (concat workspace "/utf9k/content-org/notes/"))
#+end_src
** Usability tweaks
*** How can I get Emacs to not open "find file" when double tapping <SPC>?
#+begin_src emacs-lisp
(map! :after ivy
      :map ivy-minibuffer-map
      "S-SPC" nil)
#+end_src
*** I want a glowy line to appear when I move my cursor
#+begin_src emacs-lisp
(beacon-mode 1)
#+end_src
* org-mode
** Shared settings
#+begin_src emacs-lisp
(after! org
  (setq org-directory        dropbox-org
        org-ellipsis         "⤵"))
#+end_src
** Capture templates
#+begin_src emacs-lisp
(after! org
  (setq org-capture-templates
        `(("w" "weekly review" entry
           (file+olp+datetree ,(concat dropbox-org "reviews/weekly.org"))
           (file ,(concat dropbox-tmpl "weekly_review.org"))
           :immediate-finish t)
          ("h" "horizons review" entry
           (file+olp+datetree ,(concat dropbox-org "reviews/horizons.org"))
           (file ,(concat dropbox-tmpl "horizon_review.org"))
           :immediate-finish t :tree-type month))))
#+end_src
