:DOC-CONFIG:
#+startup: fold
#+property: header-args:emacs-lisp :tangle config.el
#+property: header-args :mkdirp yes :comments no
:END:

#+title: Doom Emacs config
#+author: Marcus Crane
#+email: marcus@utf9k.net

* Core setup
** [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Lexical-Binding.html][Lexical binding]]
#+begin_src emacs-lisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+end_src
** Who am I?

#+begin_src emacs-lisp
(setq user-full-name "Marcus Crane"
      user-mail-address "marcus@utf9k.net")
#+end_src
** Netocean
I store all of my org files on a [[https://www.synology.com/en-nz/products/DS220j][Synology DS220j]] at my house, which has redundancy thanks to RAID and just to be extra safe, also syncs content with Dropbox as a backup point.

The Synology NAS has a webdav server which is what I mount to my computers and then sync files locally, not unlike Dropbox, thanks to [[https://mountainduck.io/][Mountain Duck]].

As for the name, Netocean is just the dorky name I use to refer to my personal file storage. It's short for network ocean (ie an ocean of files) and is [[https://wikimon.net/Net_Ocean][totally not taken from Digimon]].

#+begin_src emacs-lisp
(setq netocean "~/netocean")
#+end_src

* Org mode
** Setting up
*** Where do my org files live?
#+begin_src emacs-lisp
(after! org
  (setq org-directory (concat netocean "/org/")))
#+end_src

*** Where should org look for tasks?

I keep my task lists in their own folder called ~gtd~, even if I'm not strictly practicing GTD.

#+begin_src emacs-lisp
(after! org
  (setq org-agenda-directory org-directory
        org-agenda-files
        `(,(concat org-agenda-directory "adventures.org")
          ,(concat org-agenda-directory "cal-errands.org")
          ,(concat org-agenda-directory "habits.org")
          ,(concat org-agenda-directory "inbox.org")
          ,(concat org-agenda-directory "projects.org")
          ,(concat org-agenda-directory "cal-notices.org")
          ,(concat org-agenda-directory "cal-pagerduty.org")
          ,(concat org-agenda-directory "someday.org")
          ,(concat org-agenda-directory "tickler.org")
          ,(concat org-agenda-directory "cal-work.org")
          )))
#+end_src

*** What do we do with completed tasks?

Once a task is finished, it's nicer to keep it stored in an archive somewhere rather than just straight up deleting it.

#+begin_src emacs-lisp
(after! org
  (setq org-archive-location
        (concat org-agenda-directory "archive/archive-"
                (format-time-string "%Y%m" (current-time))
                ".org::")))
#+end_src
** Workflow
*** What statuses can a task have?

I try to keep this to a minimum for the sake of simplicity

#+begin_src emacs-lisp
(after! org
  (setq org-todo-keywords
        '((sequence
           "TODO(t)"
           "NEXT(n)"
           "|"
           "DONE(d)")
          (sequence
           "WAITING(w@/!)"))))
#+end_src

*** What tags can a task have?

As above, I also try to keep these as basic as possible

#+begin_src emacs-lisp
(after! org
  (setq org-tag-alist
        '(("@errand" . ?e)
          ("@home"   . ?h)
          ("@office" . ?o))))
#+end_src
*** Where can tasks be refiled?
It isn't too useful to allow refiling at more than a few levels of depth so we want to restrict some items to top level at most.

#+begin_src emacs-lisp
(after! org
  (setq org-refile-targets
        `((,(concat org-agenda-directory "ideas.org") :level . 0)
          (,(concat org-agenda-directory "projects.org") :maxlevel . 2)
          (,(concat org-agenda-directory "someday.org") :level . 0)
          (,(concat org-agenda-directory "tickler.org") :maxlevel . 1))))
#+end_src
** Quality of life
*** How can I hide items scheduled for the future?

These aren't super useful as they tend to be too far off as to be unactionable

#+begin_src emacs-lisp
(after! org (setq org-agenda-todo-ignore-scheduled 'future))
#+end_src
*** How can I speed up item entry?
We can use capture templates to speed up the process of saving items

#+begin_src emacs-lisp
(after! org
  (setq org-capture-templates
        `(("i" "inbox" entry
           (file ,(concat org-agenda-directory "inbox.org"))
           "* TODO %i%?")
          )))
#+end_src
** Modules
*** How can I track habits with org?
#+begin_src emacs-lisp
(after! org
  (require 'org-habit)
  (add-to-list 'org-modules 'org-habit))
#+end_src
* Calendar
While macOS does support showing your local calendar inline, there are some benefits to having your calendar as an org file, such as the ability to associate notes or lists with events.

Personally, I use [[https://fastmail.com][Fastmail]] which includes a caldav endpoint so I'm using ~org-caldav~

Before we dive into configuration, I'll set up my actual calendars separately for readability

** What calendars do I want to sync?
#+begin_src emacs-lisp
(after! org
  (setq org-cal-cache (concat org-agenda-directory "caches/")
        org-cal-list `(
                       (:calendar-id "12a4af42-ca44-455a-a935-d10eb99b93aa"
                        :sync 'cal->org
                        :inbox ,(concat org-agenda-directory "cal-adventures.org"))
                       (:calendar-id "D43720AE-4BFE-4026-92E3-514FABD36D31"
                        :sync 'cal->org
                        :inbox ,(concat org-agenda-directory "cal-errands.org"))
                       (:calendar-id "571F4C73-A096-4293-B961-75391E213A87"
                        :sync 'cal->org
                        :inbox ,(concat org-agenda-directory "cal-notices.org"))
                       (:calendar-id "367e7e37-1def-4f23-aac7-3af7a6e87f76"
                        :sync 'cal->org
                        :inbox ,(concat org-agenda-directory "cal-pagerduty.org"))
                       (:calendar-id "95f79eb1-f737-48c2-9c14-0958a75d73a1"
                        :sync 'cal->org
                        :inbox ,(concat org-agenda-directory "cal-work.org"))
                       )))
#+end_src

** How do we sync them?

#+begin_src emacs-lisp
(use-package org-caldav
  :defer 3
  :after org
  :config
  (setq org-caldav-url "https://caldav.fastmail.com/dav/calendars/user/marcus@utf9k.net"
        org-caldav-calendars org-cal-list
        org-caldav-delete-org-entries 'never
        org-caldav-resume-aborted 'never
        org-caldav-save-directory org-cal-cache))
#+end_src
* Extra Doom setup
While still technically part of [[#core-setup][Core setup]], I've stuck this configuration at the bottom purely because of how long it is.

** What Doom modules do we want to initialise?
#+begin_src emacs-lisp :tangle init.el
;;; init.el -*- lexical-binding: t; -*-

;; This file controls what Doom modules are enabled and what order they load
;; in. Remember to run 'doom sync' after modifying it!

;; NOTE Press 'SPC h d h' (or 'C-h d h' for non-vim users) to access Doom's
;;      documentation. There you'll find a "Module Index" link where you'll find
;;      a comprehensive list of Doom's modules and what flags they support.

;; NOTE Move your cursor over a module's name (or its flags) and press 'K' (or
;;      'C-c c k' for non-vim users) to view its documentation. This works on
;;      flags as well (those symbols that start with a plus).
;;
;;      Alternatively, press 'gd' (or 'C-c c d') on a module to browse its
;;      directory (for easy access to its source code).

(doom! :input
       ;;chinese
       ;;japanese
       ;;layout            ; auie,ctsrnm is the superior home row

       :completion
       company           ; the ultimate code completion backend
       ;;helm              ; the *other* search engine for love and life
       ;;ido               ; the other *other* search engine...
       ivy               ; a search engine for love and life

       :ui
       ;;deft              ; notational velocity for Emacs
       doom              ; what makes DOOM look the way it does
       doom-dashboard    ; a nifty splash screen for Emacs
       doom-quit         ; DOOM quit-message prompts when you quit Emacs
       (emoji +unicode)  ; 🙂
       ;;fill-column       ; a `fill-column' indicator
       hl-todo           ; highlight TODO/FIXME/NOTE/DEPRECATED/HACK/REVIEW
       ;;hydra
       ;;indent-guides     ; highlighted indent columns
       ;;ligatures         ; ligatures and symbols to make your code pretty again
       ;;minimap           ; show a map of the code on the side
       modeline          ; snazzy, Atom-inspired modeline, plus API
       ;;nav-flash         ; blink cursor line after big motions
       ;;neotree           ; a project drawer, like NERDTree for vim
       ophints           ; highlight the region an operation acts on
       (popup +defaults)   ; tame sudden yet inevitable temporary windows
       ;;tabs              ; a tab bar for Emacs
       treemacs            ; a project drawer, like neotree but cooler
       ;;unicode           ; extended unicode support for various languages
       vc-gutter         ; vcs diff in the fringe
       vi-tilde-fringe   ; fringe tildes to mark beyond EOB
       ;;window-select     ; visually switch windows
       workspaces        ; tab emulation, persistence & separate workspaces
       ;;zen               ; distraction-free coding or writing

       :editor
       (evil +everywhere); come to the dark side, we have cookies
       file-templates    ; auto-snippets for empty files
       fold              ; (nigh) universal code folding
       (format +onsave)  ; automated prettiness
       ;;god               ; run Emacs commands without modifier keys
       ;;lispy             ; vim for lisp, for people who don't like vim
       ;;multiple-cursors  ; editing in many places at once
       ;;objed             ; text object editing for the innocent
       ;;parinfer          ; turn lisp into python, sort of
       ;;rotate-text       ; cycle region at point between text candidates
       snippets          ; my elves. They type so I don't have to
       ;;word-wrap         ; soft wrapping with language-aware indent

       :emacs
       dired             ; making dired pretty [functional]
       electric          ; smarter, keyword-based electric-indent
       ;;ibuffer         ; interactive buffer management
       (undo +tree)      ; persistent, smarter undo for your inevitable mistakes TODO: Check extra config suggestions
       vc                ; version-control and Emacs, sitting in a tree

       :term
       ;;eshell            ; the elisp shell that works everywhere
       ;;shell             ; simple shell REPL for Emacs
       ;;term              ; basic terminal emulator for Emacs
       ;;vterm             ; the best terminal emulation in Emacs

       :checkers
       syntax              ; tasing you for every semicolon you forget
       ;;spell             ; tasing you for misspelling mispelling
       ;;grammar           ; tasing grammar mistake every you make

       :tools
       ;;ansible
       ;;debugger          ; FIXME stepping through code, to help you add bugs
       ;;direnv
       ;;docker
       editorconfig      ; let someone else argue about tabs vs spaces
       ;;ein               ; tame Jupyter notebooks with emacs
       (eval +overlay)     ; run code, run (also, repls)
       ;;gist              ; interacting with github gists
       lookup              ; navigate your code and its documentation
       lsp
       magit             ; a git porcelain for Emacs
       ;;make              ; run make tasks from Emacs
       ;;pass              ; password manager for nerds
       ;;pdf               ; pdf enhancements
       ;;prodigy           ; FIXME managing external services & code builders
       ;;rgb               ; creating color strings
       ;;taskrunner        ; taskrunner for all your projects
       ;;terraform         ; infrastructure as code
       ;;tmux              ; an API for interacting with tmux
       ;;upload            ; map local to remote projects via ssh/ftp

       :os
       (:if IS-MAC macos)  ; improve compatibility with macOS
       ;;tty               ; improve the terminal Emacs experience

       :lang
       ;;agda              ; types of types of types of types...
       ;;cc                ; C/C++/Obj-C madness
       ;;clojure           ; java with a lisp
       ;;common-lisp       ; if you've seen one lisp, you've seen them all
       ;;coq               ; proofs-as-programs
       ;;crystal           ; ruby at the speed of c
       ;;csharp            ; unity, .NET, and mono shenanigans
       data              ; config/data formats
       ;;(dart +flutter)   ; paint ui and not much else
       ;;elixir            ; erlang done right
       ;;elm               ; care for a cup of TEA?
       emacs-lisp        ; drown in parentheses
       ;;erlang            ; an elegant language for a more civilized age
       ;;ess               ; emacs speaks statistics
       ;;faust             ; dsp, but you get to keep your soul
       ;;fsharp            ; ML stands for Microsoft's Language
       ;;fstar             ; (dependent) types and (monadic) effects and Z3
       ;;gdscript          ; the language you waited for
       (go +lsp)         ; the hipster dialect
       ;;(haskell +dante)  ; a language that's lazier than I am
       ;;hy                ; readability of scheme w/ speed of python
       ;;idris             ; a language you can depend on
       json              ; At least it ain't XML
       ;;(java +meghanada) ; the poster child for carpal tunnel syndrome
       (javascript +lsp)   ; all(hope(abandon(ye(who(enter(here))))))
       ;;julia             ; a better, faster MATLAB
       ;;kotlin            ; a better, slicker Java(Script)
       ;;latex             ; writing papers in Emacs has never been so fun
       ;;lean
       ;;factor
       ledger            ; an accounting system in Emacs
       ;;lua               ; one-based indices? one-based indices
       markdown          ; writing docs for people to ignore
       ;;nim               ; python + lisp at the speed of c
       ;;nix               ; I hereby declare "nix geht mehr!"
       ;;ocaml             ; an objective camel
       org               ; organize your plain life in plain text
       ;;php               ; perl's insecure younger brother
       ;;plantuml          ; diagrams for confusing people more
       ;;purescript        ; javascript, but functional
       (python +lsp)       ; beautiful is better than ugly
       ;;qt                ; the 'cutest' gui framework ever
       ;;racket            ; a DSL for DSLs
       ;;raku              ; the artist formerly known as perl6
       rest              ; Emacs as a REST client
       ;;rst               ; ReST in peace
       ;;(ruby +rails)     ; 1.step {|i| p "Ruby is #{i.even? ? 'love' : 'life'}"}
       ;;rust              ; Fe2O3.unwrap().unwrap().unwrap().unwrap()
       ;;scala             ; java, but good
       ;;scheme            ; a fully conniving family of lisps
       sh                ; she sells {ba,z,fi}sh shells on the C xor
       ;;sml
       ;;solidity          ; do you need a blockchain? No.
       ;;swift             ; who asked for emoji variables?
       ;;terra             ; Earth and Moon in alignment for performance.
       web               ; the tubes
       yaml              ; JSON, but readable

       :email
       ;;(mu4e +gmail)
       ;;notmuch
       ;;(wanderlust +gmail)

       :app
       ;;calendar
       ;;irc               ; how neckbeards socialize
       ;;(rss +org)        ; emacs as an RSS reader
       ;;twitter           ; twitter client https://twitter.com/vnought

       :config
       ;;literate
       (default +bindings +smartparens))
#+end_src
** What extra packages do we want to install?
#+begin_src emacs-lisp :tangle packages.el
;; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el

;; To install a package with Doom you must declare them here and run 'doom sync'
;; on the command line, then restart Emacs for the changes to take effect -- or
;; use 'M-x doom/reload'.


;; To install SOME-PACKAGE from MELPA, ELPA or emacsmirror:
                                        ;(package! some-package)

;; To install a package directly from a remote git repo, you must specify a
;; `:recipe'. You'll find documentation on what `:recipe' accepts here:
;; https://github.com/raxod502/straight.el#the-recipe-format
                                        ;(package! another-package
                                        ;  :recipe (:host github :repo "username/repo"))

;; If the package you are trying to install does not contain a PACKAGENAME.el
;; file, or is located in a subdirectory of the repo, you'll need to specify
;; `:files' in the `:recipe':
                                        ;(package! this-package
                                        ;  :recipe (:host github :repo "username/repo"
                                        ;           :files ("some-file.el" "src/lisp/*.el")))

;; If you'd like to disable a package included with Doom, you can do so here
;; with the `:disable' property:
                                        ;(package! builtin-package :disable t)

;; You can override the recipe of a built in package without having to specify
;; all the properties for `:recipe'. These will inherit the rest of its recipe
;; from Doom or MELPA/ELPA/Emacsmirror:
                                        ;(package! builtin-package :recipe (:nonrecursive t))
                                        ;(package! builtin-package-2 :recipe (:repo "myfork/package"))

;; Specify a `:branch' to install a package from a particular branch or tag.
;; This is required for some packages whose default branch isn't 'master' (which
;; our package manager can't deal with; see raxod502/straight.el#279)
                                        ;(package! builtin-package :recipe (:branch "develop"))

;; Use `:pin' to specify a particular commit to install.
                                        ;(package! builtin-package :pin "1a2b3c4d5e")


;; Doom's packages are pinned to a specific commit and updated from release to
;; release. The `unpin!' macro allows you to unpin single packages...
                                        ;(unpin! pinned-package)
;; ...or multiple packages
                                        ;(unpin! pinned-package another-pinned-package)
;; ...Or *all* packages (NOT RECOMMENDED; will likely break things)
                                        ;(unpin! t)
(package! org-caldav)
#+end_src

* Local variables
In lieu of using Doom Emacs to automatically tangle this file, I instead just invoke ~org-babel-tangle~ anytime I save the file.
# Local Variables:
# eval: (add-hook 'after-save-hook (lambda ()(org-babel-tangle)) nil t)
# End:
