# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  - trigger: ":em"
    replace: "email:"

  - trigger: ":wt"
    replace: "waiting:"

  - trigger: ":re"
    replace: "review:"
  
  - trigger: ":wc"
    replace: "watch:"

  # And much more! For more information, visit the docs: https://espanso.org/docs/