[tools]
awscli = '2.13.38'
bun = '1.0.7'
container-diff = '0.17.0'
crystal = '1.9.2'
cue = '0.6.0'
deno = '1.37.2'
dive = '0.11.0'
dotenv-linter = '3.3.0'
github-markdown-toc = '1.2.0'
golang = '1.21.3'
goreleaser = '1.21.2'
ghorg = '1.9.9'
hugo = '0.119.0'
lua = '5.4.3'
neovim = '0.9.2'
nodejs = '20.8.0'
php = '8.2.11'
python = '3.11.0'
ruby = 'jruby-9.4.0.0'
rust = 'nightly'
shellcheck = '0.9.0'
shellspec = '0.28.1'
sqlite = '3.43.1'
terraform = '1.5.7'
tmux = '3.3'