name: Run shellcheck on shell scripts
on: [push]
jobs:
  lint:
    name: Run shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Shellcheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -P **/*.sh